create table trn_dmm_items (
  id uuid default gen_random_uuid() primary key,
  content_id text unique not null,
  product_id text,
  title text,
  volume text,
  review_count integer,
  review_average numeric,
  item_url text,
  affiliate_url text,
  image_list_url text,
  image_large_url text,
  sample_images text[],
  price integer,
  list_price integer,
  release_date text,
  genre_ids integer[],
  genres text[],
  series text,
  maker text,
  raw_json jsonb,
  created_at timestamp with time zone default now()
);
